import Head from "next/head";
import HeaderComponent from "../components/headerComponent";
import HeroComponent from "../components/heroComponent";
import MainComponent from "../components/mainComponent";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BEJAMAS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeaderComponent />
        <HeroComponent />
        <MainComponent />
      </main>
    </div>
  );
}
